name: On Release, deploying to Prod
on:
  release:
    types: [published]
jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@main
    with:
      process_env: Prod
      python_versions: '3'
    secrets: inherit
